#!/bin/bash
# IRONCLAW CI/CD Audit Pipeline v1.0
# Usage: ./audit_pipeline.sh <contract_address> [rpc_url]
# Runs all automated checks and generates a report

set -e

ADDR=${1:-"0x0A7272e8573aea8359FEC143ac02AED90F822bD0"}
RPC=${2:-"https://ethereum-rpc.publicnode.com"}
REPORT_DIR="./audit_reports"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
REPORT="$REPORT_DIR/audit_${ADDR:0:10}_${TIMESTAMP}.md"

mkdir -p "$REPORT_DIR"

echo "# IRONCLAW Automated Audit Report" > "$REPORT"
echo "## Contract: $ADDR" >> "$REPORT"
echo "**Date:** $(date -u '+%Y-%m-%d %H:%M UTC')" >> "$REPORT"
echo "**RPC:** $RPC" >> "$REPORT"
echo "" >> "$REPORT"

echo "### Step 1: Bytecode Analysis" >> "$REPORT"
python3 -c "
from web3 import Web3
w3 = Web3(Web3.HTTPProvider('$RPC', request_kwargs={'timeout': 15}))
addr = Web3.to_checksum_address('$ADDR')
code = w3.eth.get_code(addr)
print(f'- Size: {len(code)} bytes')
print(f'- EIP-170: {len(code)/24576*100:.1f}%')
has_meta = 'a264' in code.hex() or 'a265' in code.hex()
print(f'- Verified: {has_meta}')
" >> "$REPORT" 2>&1

echo "" >> "$REPORT"
echo "### Step 2: Proxy Detection" >> "$REPORT"
python3 -c "
from web3 import Web3
w3 = Web3(Web3.HTTPProvider('$RPC', request_kwargs={'timeout': 15}))
addr = Web3.to_checksum_address('$ADDR')
code = w3.eth.get_code(addr)
hex_code = code.hex()
if '363d3d373d3d3d363d73' in hex_code:
    idx = hex_code.index('363d3d373d3d3d363d73') + 20
    impl = Web3.to_checksum_address('0x' + hex_code[idx:idx+40])
    print(f'- Type: ERC-1167 Minimal Proxy')
    print(f'- Implementation: {impl}')
else:
    EIP1967 = '0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc'
    impl_raw = w3.eth.get_storage_at(addr, EIP1967)
    if int(impl_raw.hex(), 16) > 0:
        impl = Web3.to_checksum_address('0x' + impl_raw.hex()[-40:])
        print(f'- Type: EIP-1967 Proxy')
        print(f'- Implementation: {impl}')
    else:
        print(f'- Type: Not a proxy (implementation)')
" >> "$REPORT" 2>&1

echo "" >> "$REPORT"
echo "### Step 3: Security Checks" >> "$REPORT"
python3 -c "
from web3 import Web3
w3 = Web3(Web3.HTTPProvider('$RPC', request_kwargs={'timeout': 15}))
addr = Web3.to_checksum_address('$ADDR')
code = w3.eth.get_code(addr)
cb = bytes.fromhex(code.hex().replace('0x',''))
# Count dangerous opcodes
sd = sum(1 for i in range(len(cb)) if cb[i] == 0xff and not (i > 0 and 0x60 <= cb[i-1] <= 0x7f))
cc = sum(1 for i in range(len(cb)) if cb[i] == 0xf2 and not (i > 0 and 0x60 <= cb[i-1] <= 0x7f))
origin = sum(1 for i in range(len(cb)) if cb[i] == 0x32 and not (i > 0 and 0x60 <= cb[i-1] <= 0x7f))
print(f'- SELFDESTRUCT: {sd}')
print(f'- CALLCODE: {cc}')
print(f'- tx.origin: {origin}')
bal = w3.from_wei(w3.eth.get_balance(addr), 'ether')
print(f'- Balance: {bal} ETH')
" >> "$REPORT" 2>&1

echo "" >> "$REPORT"
echo "---" >> "$REPORT"
echo "*Generated by IRONCLAW CI/CD Audit Pipeline v1.0*" >> "$REPORT"

echo "Report saved: $REPORT"
cat "$REPORT"
